### ISSUE TITLE
Problem in SpeechController

### ISSUE THREAD

**Issue by vijaykharage** [algolia/voice-overlay-ios#10]
After recording has done I want to speak out loud the text what I just said. But I guess there is still SpeechController running in background even though SpeechController.stopRecording() method calls from deinit. 
I am trying to use this code 

```
let string = "Hello, World!"
let utterance = AVSpeechUtterance(string: string)
utterance.voice = AVSpeechSynthesisVoice(language: "en-US")

let synth = AVSpeechSynthesizer()
synth.speak(utterance)
```

But no utterance is happening. Please help me.

**Comment by spinach** [comment]
Hey @vijaykharage ,

I just quickly tested your snippet in the demo project by adding your sample in the `textHandler` and it worked fine (I could hear the "Hello World!". Do you have some sample code project so that we can reproduce the issue?

**Comment by vijaykharage** [comment]
Please tell me that, are you testing it as soon as the recording has finished? Because I am and not hearing anything rather I ran it in another viewController and it does well (Before recording anything).

**Comment by spinach** [comment]
Yes, I am testing it in the handler as soon as it is finished, and it works fine in the demo. Check in the `speech_test` branch, the demo. This is the [line](https://github.com/algolia/voice-overlay-ios/blob/speak_test/VoiceOverlay-Demo/VoiceOverlay-Demo/ViewController.swift#L88) concerned. You can checkout the branch and run the demo and see for yourself

**Comment by vijaykharage** [comment]
Yes I am trying the same but it seems like I am having a different problem. Sending you video regarding same. Look at the music widget at first before recording screen. As soon as I start recording the music widget gets icon at it's upper right corner showing phone is listening and never goes off from that state even after stopping the recording.
![ezgif-4-da283ecb5daf](https://user-images.githubusercontent.com/31646541/49433516-42c4f200-f7d8-11e8-8f7f-181044464c42.gif)
 I guess the microphone is not disabling even though recording has stopped.

**Comment by vijaykharage** [comment]
Did the same. It is running perfectly fine on simulator but in device there is something weird stuff I am seeing. Please look following GIF.
![ezgif-4-da283ecb5daf](https://user-images.githubusercontent.com/31646541/49441853-bf160000-f7ed-11e8-86d8-28bbad1807be.gif)

The music widget is looking fine. But after I press mic button and then see that music widget, some icon appear on upper right corner. I guess the app is still listening. Any suggestions would be very appreciated.

**Comment by spinach** [comment]
I see, that's weird.. In order to debug, I suggest you check [this part of the README](https://github.com/algolia/voice-overlay-ios/blob/master/README.md#changing-locale-or-speechcontroller) to have access to the SpeechController under the hood. Then you can debug and try to stop the speech controller manually, and see if this fixes the issue? Let me know what you find out.
