### ISSUE TITLE
Unable to access settings and init with locale using Objective-C

### ISSUE THREAD

**Issue by hktvmall** [algolia/voice-overlay-ios#13]
```
#import "InstantSearchVoiceOverlay-Swift.h"

// can only use init 
VoiceOverlayController *voiceOverlayController = [[VoiceOverlayController alloc] init]; 

// error
voiceOverlayController.settings.autoStopTimeout = 0.5;

// *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<InstantSearchVoiceOverlay.VoiceOverlayController 0x2827adb80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key settings.'
[voiceOverlayController setValue:@(0.5) forKeyPath:@"settings.autoStopTimeout"]
```

**Comment by spinach** [comment]
Hello,

Sorry for missing this issue. Were you able to solve this issue? Let us know if you still need help by re-opening this

**Comment by valnenov** [comment]
Hi, I have question unrelated to the above topic. In my app I am using AVAudioPlayer to play sounds. After I added the InstantSearchVoiceOverlay functionality I can no longer play the sounds once the VoiceOverlayController has been initialized/used. What can  I do to remedy this problem? Can you please help?
