### ISSUE TITLE
Crash when first request permission

### ISSUE THREAD

**Issue by fadielse** [algolia/voice-overlay-ios#22]
hi thanks for this cool library, but I found a problem when my serachController is in the tabBarController

when it was my first request for permission and I allowed it, the application crashed and after the application was reopened everything went smoothly. but then the problem arises again because when the input page appears the menu on the tabbar is not overwritten like the permission page.

I really appreciate if you help me solve the problem, cheers

**Comment by marcelfagadariu** [comment]
> hi thanks for this cool library, but I found a problem when my serachController is in the tabBarController
> 
> when it was my first request for permission and I allowed it, the application crashed and after the application was reopened everything went smoothly. but then the problem arises again because when the input page appears the menu on the tabbar is not overwritten like the permission page.
> 
> I really appreciate if you help me solve the problem, cheers

Hey. Did you solve this issue? It still crashes my app for the first time when it request permissios

**Comment by ShaiAlkoby** [comment]
@marcelfagadariu @fadielse did any of you manage to solve this problem?

**Comment by marcelfagadariu** [comment]
> @marcelfagadariu @fadielse did any of you manage to solve this problem?

Sadly, no, still crashing. Any idea if any delegate method is called if the close button is pressed? Can't find any

**Comment by vuongle1705** [comment]
Yes, I met the same issue. I've tried in iOS 12 and iOS 13 as well, I think this bug only happens with iOS 13. I didnt met this bug in iOS 12.

**Comment by selini** [comment]
Same here. I have the same issue in iOS 13

**Comment by fadielse** [comment]
> hi thanks for this cool library, but I found a problem when my serachController is in the tabBarController
> 
> when it was my first request for permission and I allowed it, the application crashed and after the application was reopened everything went smoothly. but then the problem arises again because when the input page appears the menu on the tabbar is not overwritten like the permission page.
> 
> I really appreciate if you help me solve the problem, cheers

apparently there are many who experienced the same thing with me.

waiting for the fix for the bug, I tried to request permissions outside of this library and it worked.

maybe a little sample of my code:

```
import AVFoundation
import Speech

//put this code whereever you want ex: appdelegate / voice page
AVAudioSession.sharedInstance (). RequestRecordPermission {_ in}
SFSpeechRecognizer.requestAuthorization {_ in}
```

**Comment by spinach** [comment]
Hello,

Sorry for the very late reply here. Just submitted `version 1.1.0` that should fix the issue. You can run `pod update` to get it. Cheers!
