### ISSUE TITLE
How to recognize language other than english?

### ISSUE THREAD

**Issue by vijaykharage** [algolia/voice-overlay-ios#8]
I am trying to recognize text which is spoken in spanish. But the controller is detecting only english language. Please help me.

**Comment by spinach** [comment]
Hey @vijaykharage 

Great question, I just added a section on the [README](https://github.com/algolia/voice-overlay-ios#changing-locale) for how to deal with different locales. 

Cheers!

**Comment by vijaykharage** [comment]
Thanks for the quick help. Greatly appreciated.
