### ISSUE TITLE
How to remove "subtitleBulletLabel" from recording screen?

### ISSUE THREAD

**Issue by vijaykharage** [algolia/voice-overlay-ios#9]
Hi,
Tried removing subtitleBulletLabel from RecordingViewController but it is not getting off. Can you please tell me how to remove it?
Thanks

**Comment by spinach** [comment]
Hey @vijaykharage,

You should set those to empty:

```swift
  /// Subtitle shown at the top of the screen before the recording button is activated.
  public var subtitleInitial = "Say something like:"
  
  /// The bullet point shown for each item in the list of suggestions
  public var subtitleBullet = "\u{2022}"
  
  /// The list of query suggestions shown in a bullet list
  public var subtitleBulletList = ["\"iphone case\"", "\"Running shoes\""]
```

**Comment by vijaykharage** [comment]
It's not working.
![screen shot 2018-11-30 at 4 10 50 pm](https://user-images.githubusercontent.com/31646541/49284418-8e1a9000-f4ba-11e8-93f6-6f4a75dca222.png)

Even though removing them completely from RecordingViewController they appear in recording screen out of nowhere.

**Comment by spinach** [comment]
In your viewController, if you do the following, it should work. I just tested it out. 

```swift
    voiceOverlayController.settings.layout.inputScreen.subtitleInitial = ""
    voiceOverlayController.settings.layout.inputScreen.subtitleBullet = ""
    voiceOverlayController.settings.layout.inputScreen.subtitleBulletList = []
```

![image](https://user-images.githubusercontent.com/1502519/49285320-69f98780-f497-11e8-8ea5-ef6fc8d2e4b9.png)
